version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-change-this-secret-key}
      - FLASK_DEBUG=false
      - DATABASE_PATH=/app/data/tracking.db
    volumes:
      - tracking_data:/app/data
    command: python app.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  bot:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}
      - DATABASE_PATH=/app/data/tracking.db
    volumes:
      - tracking_data:/app/data
    command: python bot.py
    restart: unless-stopped
    depends_on:
      - web

volumes:
  tracking_data:
    driver: local 